[package]
name = "network-error-logging"
version = "0.1.0"
authors = ["Patrick Hamann <patrick@fastly.com>"]
edition = "2018"

[profile.release]
debug = true

[dependencies]
base64 = "0.13.0"
fastly = "0.7.1"
getrandom = "0.2.3"
lol_html = "0.3.0"
