authors = ["denis@cornehl.org"]
description = "generate a CSP nonce, set CSP headers and rewrite the HTML to include the nonce in script tags"
language = "rust"
manifest_version = 1
name = "docs-rs-fastly-csp"
service_id = "2uZzD8OMOv1h8M02soELwc"
